version: '3'
services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
  # webapp:
  #   build:
  #     context: ./webapp
  #     dockerfile: Dockerfile
  #   container_name: webapp
  #   ports:
  #     - "8080:8080"
  #     - "3000:3000"
  #   volumes:
  #     - "./webapp/app:/app"
  #   tty:
  #     true
