FROM node:18-alpine

WORKDIR /app

RUN npm install -g @vue/cli

COPY ./scripts/docker.start.sh /scripts/start.sh

#shフォルダの権限追加（全員実行可）
RUN chmod +x /scripts/*

# ENTRYPOINT [ "/scripts/start.sh" ]